/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedOperationsRouteImport } from './routes/_authenticated.operations'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated.approvals'
import { Route as AuthenticatedPedidosVendaIndexRouteImport } from './routes/_authenticated.pedidos-venda.index'
import { Route as ApiPublicTmpResetAdminRouteImport } from './routes/api/public/tmp-reset-admin'
import { Route as AuthenticatedSettingsErpRouteImport } from './routes/_authenticated.settings.erp'
import { Route as AuthenticatedPedidosVendaNovoRouteImport } from './routes/_authenticated.pedidos-venda.novo'
import { Route as AuthenticatedPedidosVendaAprovacoesRouteImport } from './routes/_authenticated.pedidos-venda.aprovacoes'
import { Route as AuthenticatedPedidosVendaDraftIdRouteImport } from './routes/_authenticated.pedidos-venda.$draftId'
import { Route as AuthenticatedOrdersSplatRouteImport } from './routes/_authenticated.orders.$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPedidosVendaIndexRoute =
  AuthenticatedPedidosVendaIndexRouteImport.update({
    id: '/pedidos-venda/',
    path: '/pedidos-venda/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicTmpResetAdminRoute = ApiPublicTmpResetAdminRouteImport.update({
  id: '/api/public/tmp-reset-admin',
  path: '/api/public/tmp-reset-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsErpRoute =
  AuthenticatedSettingsErpRouteImport.update({
    id: '/settings/erp',
    path: '/settings/erp',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPedidosVendaNovoRoute =
  AuthenticatedPedidosVendaNovoRouteImport.update({
    id: '/pedidos-venda/novo',
    path: '/pedidos-venda/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPedidosVendaAprovacoesRoute =
  AuthenticatedPedidosVendaAprovacoesRouteImport.update({
    id: '/pedidos-venda/aprovacoes',
    path: '/pedidos-venda/aprovacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPedidosVendaDraftIdRoute =
  AuthenticatedPedidosVendaDraftIdRouteImport.update({
    id: '/pedidos-venda/$draftId',
    path: '/pedidos-venda/$draftId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersSplatRoute =
  AuthenticatedOrdersSplatRouteImport.update({
    id: '/orders/$',
    path: '/orders/$',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/orders/$': typeof AuthenticatedOrdersSplatRoute
  '/pedidos-venda/$draftId': typeof AuthenticatedPedidosVendaDraftIdRoute
  '/pedidos-venda/aprovacoes': typeof AuthenticatedPedidosVendaAprovacoesRoute
  '/pedidos-venda/novo': typeof AuthenticatedPedidosVendaNovoRoute
  '/settings/erp': typeof AuthenticatedSettingsErpRoute
  '/api/public/tmp-reset-admin': typeof ApiPublicTmpResetAdminRoute
  '/pedidos-venda/': typeof AuthenticatedPedidosVendaIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/': typeof AuthenticatedIndexRoute
  '/orders/$': typeof AuthenticatedOrdersSplatRoute
  '/pedidos-venda/$draftId': typeof AuthenticatedPedidosVendaDraftIdRoute
  '/pedidos-venda/aprovacoes': typeof AuthenticatedPedidosVendaAprovacoesRoute
  '/pedidos-venda/novo': typeof AuthenticatedPedidosVendaNovoRoute
  '/settings/erp': typeof AuthenticatedSettingsErpRoute
  '/api/public/tmp-reset-admin': typeof ApiPublicTmpResetAdminRoute
  '/pedidos-venda': typeof AuthenticatedPedidosVendaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/operations': typeof AuthenticatedOperationsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/orders/$': typeof AuthenticatedOrdersSplatRoute
  '/_authenticated/pedidos-venda/$draftId': typeof AuthenticatedPedidosVendaDraftIdRoute
  '/_authenticated/pedidos-venda/aprovacoes': typeof AuthenticatedPedidosVendaAprovacoesRoute
  '/_authenticated/pedidos-venda/novo': typeof AuthenticatedPedidosVendaNovoRoute
  '/_authenticated/settings/erp': typeof AuthenticatedSettingsErpRoute
  '/api/public/tmp-reset-admin': typeof ApiPublicTmpResetAdminRoute
  '/_authenticated/pedidos-venda/': typeof AuthenticatedPedidosVendaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/approvals'
    | '/operations'
    | '/orders/$'
    | '/pedidos-venda/$draftId'
    | '/pedidos-venda/aprovacoes'
    | '/pedidos-venda/novo'
    | '/settings/erp'
    | '/api/public/tmp-reset-admin'
    | '/pedidos-venda/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/approvals'
    | '/operations'
    | '/'
    | '/orders/$'
    | '/pedidos-venda/$draftId'
    | '/pedidos-venda/aprovacoes'
    | '/pedidos-venda/novo'
    | '/settings/erp'
    | '/api/public/tmp-reset-admin'
    | '/pedidos-venda'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/approvals'
    | '/_authenticated/operations'
    | '/_authenticated/'
    | '/_authenticated/orders/$'
    | '/_authenticated/pedidos-venda/$draftId'
    | '/_authenticated/pedidos-venda/aprovacoes'
    | '/_authenticated/pedidos-venda/novo'
    | '/_authenticated/settings/erp'
    | '/api/public/tmp-reset-admin'
    | '/_authenticated/pedidos-venda/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicTmpResetAdminRoute: typeof ApiPublicTmpResetAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operations': {
      id: '/_authenticated/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos-venda/': {
      id: '/_authenticated/pedidos-venda/'
      path: '/pedidos-venda'
      fullPath: '/pedidos-venda/'
      preLoaderRoute: typeof AuthenticatedPedidosVendaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/tmp-reset-admin': {
      id: '/api/public/tmp-reset-admin'
      path: '/api/public/tmp-reset-admin'
      fullPath: '/api/public/tmp-reset-admin'
      preLoaderRoute: typeof ApiPublicTmpResetAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/erp': {
      id: '/_authenticated/settings/erp'
      path: '/settings/erp'
      fullPath: '/settings/erp'
      preLoaderRoute: typeof AuthenticatedSettingsErpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos-venda/novo': {
      id: '/_authenticated/pedidos-venda/novo'
      path: '/pedidos-venda/novo'
      fullPath: '/pedidos-venda/novo'
      preLoaderRoute: typeof AuthenticatedPedidosVendaNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos-venda/aprovacoes': {
      id: '/_authenticated/pedidos-venda/aprovacoes'
      path: '/pedidos-venda/aprovacoes'
      fullPath: '/pedidos-venda/aprovacoes'
      preLoaderRoute: typeof AuthenticatedPedidosVendaAprovacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos-venda/$draftId': {
      id: '/_authenticated/pedidos-venda/$draftId'
      path: '/pedidos-venda/$draftId'
      fullPath: '/pedidos-venda/$draftId'
      preLoaderRoute: typeof AuthenticatedPedidosVendaDraftIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/$': {
      id: '/_authenticated/orders/$'
      path: '/orders/$'
      fullPath: '/orders/$'
      preLoaderRoute: typeof AuthenticatedOrdersSplatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOrdersSplatRoute: typeof AuthenticatedOrdersSplatRoute
  AuthenticatedPedidosVendaDraftIdRoute: typeof AuthenticatedPedidosVendaDraftIdRoute
  AuthenticatedPedidosVendaAprovacoesRoute: typeof AuthenticatedPedidosVendaAprovacoesRoute
  AuthenticatedPedidosVendaNovoRoute: typeof AuthenticatedPedidosVendaNovoRoute
  AuthenticatedSettingsErpRoute: typeof AuthenticatedSettingsErpRoute
  AuthenticatedPedidosVendaIndexRoute: typeof AuthenticatedPedidosVendaIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedOperationsRoute: AuthenticatedOperationsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOrdersSplatRoute: AuthenticatedOrdersSplatRoute,
  AuthenticatedPedidosVendaDraftIdRoute: AuthenticatedPedidosVendaDraftIdRoute,
  AuthenticatedPedidosVendaAprovacoesRoute:
    AuthenticatedPedidosVendaAprovacoesRoute,
  AuthenticatedPedidosVendaNovoRoute: AuthenticatedPedidosVendaNovoRoute,
  AuthenticatedSettingsErpRoute: AuthenticatedSettingsErpRoute,
  AuthenticatedPedidosVendaIndexRoute: AuthenticatedPedidosVendaIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicTmpResetAdminRoute: ApiPublicTmpResetAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
