/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedRecolhasRouteImport } from './routes/_authenticated.recolhas'
import { Route as AuthenticatedOperationsRouteImport } from './routes/_authenticated.operations'
import { Route as AuthenticatedEntregasRouteImport } from './routes/_authenticated.entregas'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated.approvals'
import { Route as AuthenticatedPedidosVendaIndexRouteImport } from './routes/_authenticated.pedidos-venda.index'
import { Route as ApiPublicTmpResetAdminRouteImport } from './routes/api/public/tmp-reset-admin'
import { Route as AuthenticatedSettingsMapaRouteImport } from './routes/_authenticated.settings.mapa'
import { Route as AuthenticatedSettingsErpRouteImport } from './routes/_authenticated.settings.erp'
import { Route as AuthenticatedSettingsCatalogoRouteImport } from './routes/_authenticated.settings.catalogo'
import { Route as AuthenticatedPedidosVendaNovoRouteImport } from './routes/_authenticated.pedidos-venda.novo'
import { Route as AuthenticatedPedidosVendaAprovacoesRouteImport } from './routes/_authenticated.pedidos-venda.aprovacoes'
import { Route as AuthenticatedPedidosVendaDraftIdRouteImport } from './routes/_authenticated.pedidos-venda.$draftId'
import { Route as AuthenticatedOrdersSplatRouteImport } from './routes/_authenticated.orders.$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecolhasRoute = AuthenticatedRecolhasRouteImport.update({
  id: '/recolhas',
  path: '/recolhas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEntregasRoute = AuthenticatedEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPedidosVendaIndexRoute =
  AuthenticatedPedidosVendaIndexRouteImport.update({
    id: '/pedidos-venda/',
    path: '/pedidos-venda/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicTmpResetAdminRoute = ApiPublicTmpResetAdminRouteImport.update({
  id: '/api/public/tmp-reset-admin',
  path: '/api/public/tmp-reset-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsMapaRoute =
  AuthenticatedSettingsMapaRouteImport.update({
    id: '/settings/mapa',
    path: '/settings/mapa',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsErpRoute =
  AuthenticatedSettingsErpRouteImport.update({
    id: '/settings/erp',
    path: '/settings/erp',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsCatalogoRoute =
  AuthenticatedSettingsCatalogoRouteImport.update({
    id: '/settings/catalogo',
    path: '/settings/catalogo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPedidosVendaNovoRoute =
  AuthenticatedPedidosVendaNovoRouteImport.update({
    id: '/pedidos-venda/novo',
    path: '/pedidos-venda/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPedidosVendaAprovacoesRoute =
  AuthenticatedPedidosVendaAprovacoesRouteImport.update({
    id: '/pedidos-venda/aprovacoes',
    path: '/pedidos-venda/aprovacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPedidosVendaDraftIdRoute =
  AuthenticatedPedidosVendaDraftIdRouteImport.update({
    id: '/pedidos-venda/$draftId',
    path: '/pedidos-venda/$draftId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersSplatRoute =
  AuthenticatedOrdersSplatRouteImport.update({
    id: '/orders/$',
    path: '/orders/$',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/recolhas': typeof AuthenticatedRecolhasRoute
  '/orders/$': typeof AuthenticatedOrdersSplatRoute
  '/pedidos-venda/$draftId': typeof AuthenticatedPedidosVendaDraftIdRoute
  '/pedidos-venda/aprovacoes': typeof AuthenticatedPedidosVendaAprovacoesRoute
  '/pedidos-venda/novo': typeof AuthenticatedPedidosVendaNovoRoute
  '/settings/catalogo': typeof AuthenticatedSettingsCatalogoRoute
  '/settings/erp': typeof AuthenticatedSettingsErpRoute
  '/settings/mapa': typeof AuthenticatedSettingsMapaRoute
  '/api/public/tmp-reset-admin': typeof ApiPublicTmpResetAdminRoute
  '/pedidos-venda/': typeof AuthenticatedPedidosVendaIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/recolhas': typeof AuthenticatedRecolhasRoute
  '/': typeof AuthenticatedIndexRoute
  '/orders/$': typeof AuthenticatedOrdersSplatRoute
  '/pedidos-venda/$draftId': typeof AuthenticatedPedidosVendaDraftIdRoute
  '/pedidos-venda/aprovacoes': typeof AuthenticatedPedidosVendaAprovacoesRoute
  '/pedidos-venda/novo': typeof AuthenticatedPedidosVendaNovoRoute
  '/settings/catalogo': typeof AuthenticatedSettingsCatalogoRoute
  '/settings/erp': typeof AuthenticatedSettingsErpRoute
  '/settings/mapa': typeof AuthenticatedSettingsMapaRoute
  '/api/public/tmp-reset-admin': typeof ApiPublicTmpResetAdminRoute
  '/pedidos-venda': typeof AuthenticatedPedidosVendaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/entregas': typeof AuthenticatedEntregasRoute
  '/_authenticated/operations': typeof AuthenticatedOperationsRoute
  '/_authenticated/recolhas': typeof AuthenticatedRecolhasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/orders/$': typeof AuthenticatedOrdersSplatRoute
  '/_authenticated/pedidos-venda/$draftId': typeof AuthenticatedPedidosVendaDraftIdRoute
  '/_authenticated/pedidos-venda/aprovacoes': typeof AuthenticatedPedidosVendaAprovacoesRoute
  '/_authenticated/pedidos-venda/novo': typeof AuthenticatedPedidosVendaNovoRoute
  '/_authenticated/settings/catalogo': typeof AuthenticatedSettingsCatalogoRoute
  '/_authenticated/settings/erp': typeof AuthenticatedSettingsErpRoute
  '/_authenticated/settings/mapa': typeof AuthenticatedSettingsMapaRoute
  '/api/public/tmp-reset-admin': typeof ApiPublicTmpResetAdminRoute
  '/_authenticated/pedidos-venda/': typeof AuthenticatedPedidosVendaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/approvals'
    | '/entregas'
    | '/operations'
    | '/recolhas'
    | '/orders/$'
    | '/pedidos-venda/$draftId'
    | '/pedidos-venda/aprovacoes'
    | '/pedidos-venda/novo'
    | '/settings/catalogo'
    | '/settings/erp'
    | '/settings/mapa'
    | '/api/public/tmp-reset-admin'
    | '/pedidos-venda/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/approvals'
    | '/entregas'
    | '/operations'
    | '/recolhas'
    | '/'
    | '/orders/$'
    | '/pedidos-venda/$draftId'
    | '/pedidos-venda/aprovacoes'
    | '/pedidos-venda/novo'
    | '/settings/catalogo'
    | '/settings/erp'
    | '/settings/mapa'
    | '/api/public/tmp-reset-admin'
    | '/pedidos-venda'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/approvals'
    | '/_authenticated/entregas'
    | '/_authenticated/operations'
    | '/_authenticated/recolhas'
    | '/_authenticated/'
    | '/_authenticated/orders/$'
    | '/_authenticated/pedidos-venda/$draftId'
    | '/_authenticated/pedidos-venda/aprovacoes'
    | '/_authenticated/pedidos-venda/novo'
    | '/_authenticated/settings/catalogo'
    | '/_authenticated/settings/erp'
    | '/_authenticated/settings/mapa'
    | '/api/public/tmp-reset-admin'
    | '/_authenticated/pedidos-venda/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicTmpResetAdminRoute: typeof ApiPublicTmpResetAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recolhas': {
      id: '/_authenticated/recolhas'
      path: '/recolhas'
      fullPath: '/recolhas'
      preLoaderRoute: typeof AuthenticatedRecolhasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operations': {
      id: '/_authenticated/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/entregas': {
      id: '/_authenticated/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof AuthenticatedEntregasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos-venda/': {
      id: '/_authenticated/pedidos-venda/'
      path: '/pedidos-venda'
      fullPath: '/pedidos-venda/'
      preLoaderRoute: typeof AuthenticatedPedidosVendaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/tmp-reset-admin': {
      id: '/api/public/tmp-reset-admin'
      path: '/api/public/tmp-reset-admin'
      fullPath: '/api/public/tmp-reset-admin'
      preLoaderRoute: typeof ApiPublicTmpResetAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/mapa': {
      id: '/_authenticated/settings/mapa'
      path: '/settings/mapa'
      fullPath: '/settings/mapa'
      preLoaderRoute: typeof AuthenticatedSettingsMapaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/erp': {
      id: '/_authenticated/settings/erp'
      path: '/settings/erp'
      fullPath: '/settings/erp'
      preLoaderRoute: typeof AuthenticatedSettingsErpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/catalogo': {
      id: '/_authenticated/settings/catalogo'
      path: '/settings/catalogo'
      fullPath: '/settings/catalogo'
      preLoaderRoute: typeof AuthenticatedSettingsCatalogoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos-venda/novo': {
      id: '/_authenticated/pedidos-venda/novo'
      path: '/pedidos-venda/novo'
      fullPath: '/pedidos-venda/novo'
      preLoaderRoute: typeof AuthenticatedPedidosVendaNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos-venda/aprovacoes': {
      id: '/_authenticated/pedidos-venda/aprovacoes'
      path: '/pedidos-venda/aprovacoes'
      fullPath: '/pedidos-venda/aprovacoes'
      preLoaderRoute: typeof AuthenticatedPedidosVendaAprovacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos-venda/$draftId': {
      id: '/_authenticated/pedidos-venda/$draftId'
      path: '/pedidos-venda/$draftId'
      fullPath: '/pedidos-venda/$draftId'
      preLoaderRoute: typeof AuthenticatedPedidosVendaDraftIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/$': {
      id: '/_authenticated/orders/$'
      path: '/orders/$'
      fullPath: '/orders/$'
      preLoaderRoute: typeof AuthenticatedOrdersSplatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedEntregasRoute: typeof AuthenticatedEntregasRoute
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRoute
  AuthenticatedRecolhasRoute: typeof AuthenticatedRecolhasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOrdersSplatRoute: typeof AuthenticatedOrdersSplatRoute
  AuthenticatedPedidosVendaDraftIdRoute: typeof AuthenticatedPedidosVendaDraftIdRoute
  AuthenticatedPedidosVendaAprovacoesRoute: typeof AuthenticatedPedidosVendaAprovacoesRoute
  AuthenticatedPedidosVendaNovoRoute: typeof AuthenticatedPedidosVendaNovoRoute
  AuthenticatedSettingsCatalogoRoute: typeof AuthenticatedSettingsCatalogoRoute
  AuthenticatedSettingsErpRoute: typeof AuthenticatedSettingsErpRoute
  AuthenticatedSettingsMapaRoute: typeof AuthenticatedSettingsMapaRoute
  AuthenticatedPedidosVendaIndexRoute: typeof AuthenticatedPedidosVendaIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedEntregasRoute: AuthenticatedEntregasRoute,
  AuthenticatedOperationsRoute: AuthenticatedOperationsRoute,
  AuthenticatedRecolhasRoute: AuthenticatedRecolhasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOrdersSplatRoute: AuthenticatedOrdersSplatRoute,
  AuthenticatedPedidosVendaDraftIdRoute: AuthenticatedPedidosVendaDraftIdRoute,
  AuthenticatedPedidosVendaAprovacoesRoute:
    AuthenticatedPedidosVendaAprovacoesRoute,
  AuthenticatedPedidosVendaNovoRoute: AuthenticatedPedidosVendaNovoRoute,
  AuthenticatedSettingsCatalogoRoute: AuthenticatedSettingsCatalogoRoute,
  AuthenticatedSettingsErpRoute: AuthenticatedSettingsErpRoute,
  AuthenticatedSettingsMapaRoute: AuthenticatedSettingsMapaRoute,
  AuthenticatedPedidosVendaIndexRoute: AuthenticatedPedidosVendaIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicTmpResetAdminRoute: ApiPublicTmpResetAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
