// This file is automatically generated. Do not edit it directly.
// Helper to call workspace connectors through the Lovable AI Gateway.
import { getRequest } from '@tanstack/react-start/server'

export interface ConnectorCallOptions {
  connector_id: string;
  path: string;
  method?: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  query_params?: Record<string, any>;
  headers?: Record<string, string>;
  body?: any;
}

/**
 * Calls a workspace connector via the Lovable AI Gateway.
 * MUST be used within a server function (.middleware([requireSupabaseAuth])).
 */
export async function callConnector(options: ConnectorCallOptions): Promise<Response> {
  const LOVABLE_API_KEY = process.env.LOVABLE_API_KEY;
  const LOVABLE_GATEWAY_URL = process.env.LOVABLE_GATEWAY_URL || 'https://api.lovable.app/gateway';

  if (!LOVABLE_API_KEY) {
    throw new Error('Missing LOVABLE_API_KEY environment variable.');
  }

  const request = getRequest();
  const authHeader = request?.headers?.get('authorization');

  const url = new URL(`${LOVABLE_GATEWAY_URL}/${options.connector_id}${options.path}`);
  
  if (options.query_params) {
    Object.entries(options.query_params).forEach(([key, value]) => {
      if (Array.isArray(value)) {
        value.forEach(v => url.searchParams.append(key, String(v)));
      } else if (value !== undefined && value !== null) {
        url.searchParams.append(key, String(value));
      }
    });
  }

  const headers = new Headers(options.headers);
  headers.set('X-Lovable-Project-Id', process.env.VITE_SUPABASE_PROJECT_ID || '');
  headers.set('Authorization', `Bearer ${LOVABLE_API_KEY}`);
  
  // Forward user session if available to identify the caller in logs
  if (authHeader) {
    headers.set('X-Lovable-User-Token', authHeader.replace('Bearer ', ''));
  }

  return fetch(url.toString(), {
    method: options.method || 'GET',
    headers,
    body: options.body ? JSON.stringify(options.body) : undefined,
  });
}
